version: "2.1"

services:
  backendpy3:
    build:
      context: ./
      dockerfile: services/backendpy3/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
      elastic:
        condition: service_healthy
    ports:
      - "5000:5000"
    hostname: dcbackend

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - "54320:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

