version: "3.5.2"

services:
  englishbot:
    build:
      context: ./
      dockerfile: services/backend_py3/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    hostname: dcbackend

  tgbot:
    build:
      context: ./
      dockerfile: services/tgbot/Dockerfile
    depends_on:
      - englishbot

  db:
    image: postgres
    environment:
      POSTGRES_DB: "english"
      POSTGRES_PASSWORD: 12345678
    ports:
      - "54320:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

